_BASE_: [
    '../runtime.yml',
    './ppyoloe_adamw_flip3_clip.yml',
]
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ppyoloe_crn_x_obj365_pretrained.pdparams
depth_mult: 1.33
width_mult: 1.25
