_BASE_: [
  '../datasets/sniper_visdrone_detection.yml',
  '../runtime.yml',
  '../ppyolo/_base_/ppyolo_r50vd_dcn.yml',
  './_base_/ppyolo_reader.yml',
]
snapshot_epoch: 20
use_ema: true
weights: output/ppyolo_r50vd_dcn_1x_sniper_visdrone/model_final
epoch: 100

LearningRate:
  base_lr: 0.00005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 200
  - !LinearWarmup
    start_factor: 0.1
    steps: 4000

#OptimizerBuilder:
#  optimizer:
#    momentum: 0.9
#    type: Momentum
#  regularizer:
#    factor: 0.0005
#    type: L2

OptimizerBuilder:
  optimizer:
    type: AdamW
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01

