_BASE_: [
  '../datasets/sniper_visdrone_detection.yml',
  '../runtime.yml',
]
snapshot_epoch: 20
use_ema: true
ema_decay: 0.9998
weights: output/ppyolo_r50vd_dcn_1x_sniper_visdrone/model_final
epoch: 100

LearningRate:
  base_lr: 0.00005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 200
  - !LinearWarmup
    start_factor: 0.1
    steps: 4000

#OptimizerBuilder:
#  optimizer:
#    momentum: 0.9
#    type: Momentum
#  regularizer:
#    factor: 0.0005
#    type: L2

OptimizerBuilder:
  optimizer:
    type: AdamW
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.01

worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - SniperDecodeCrop: {}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [608, 640], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[31, 25],[54, 34],[78, 41],[54, 68],[79, 97],[165, 96],[120, 183],[275, 166],[466, 351]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - SniperDecodeCrop: {}
    - Resize: {target_size: [1600, 1600], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8

TestReader:
  sample_transforms:
    - SniperDecodeCrop: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1



architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
norm_type: sync_bn


YOLOv3:
  backbone: ResNet
  neck: PPYOLOFPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [3]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

PPYOLOFPN:
  coord_conv: true
  drop_block: true
  block_size: 3
  keep_prob: 0.9
  spp: true

YOLOv3Head:
  anchors: [[31, 25],[54, 34],[78, 41],[54, 68],[79, 97],[165, 96],[120, 183],[275, 166],[466, 351]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss
  iou_aware: true
  iou_aware_factor: 0.4

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false
  scale_x_y: 1.05
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  loss_square: true

IouAwareLoss:
  loss_weight: 1.0

BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.01
    downsample_ratio: 32
    clip_bbox: true
    scale_x_y: 1.05
  nms:
    name: MatrixNMS
    keep_top_k: 100
    score_threshold: 0.01
    post_threshold: 0.01
    nms_top_k: -1
    background_label: -1

