metric: SNIPERCOCO
num_classes: 3

TrainDataset:
  !SniperCOCODataSet
    image_dir: /mnt/DataSets/齿轮检测数据集/trainval/JPEGImages
    anno_path: /mnt/DataSets/齿轮检测数据集/trainval/train.json
    dataset_dir: /mnt/DataSets/齿轮检测数据集/trainval
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true
    is_trainset: true
    image_target_sizes: [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    use_neg_chip: false
    max_neg_num_per_im: 8


EvalDataset:
  !SniperCOCODataSet
    image_dir: /mnt/DataSets/齿轮检测数据集/trainval/JPEGImages
    anno_path: /mnt/DataSets/齿轮检测数据集/trainval/val.json
    dataset_dir: /mnt/DataSets/齿轮检测数据集/trainval
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
    allow_empty: true
    is_trainset: false
    image_target_sizes:  [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    max_per_img: -1
    nms_thresh: 0.5

TestDataset:
  !SniperCOCODataSet
    image_dir: /mnt/DataSets/齿轮检测数据集/trainval/JPEGImages
    anno_path: /mnt/DataSets/齿轮检测数据集/trainval/val.json
    dataset_dir: /mnt/DataSets/齿轮检测数据集/trainval
    is_trainset: false
    image_target_sizes:  [1600, 1600]
    valid_box_ratio_ranges: [[0.02,0.233125], [-1, -1]]
    chip_target_size: 800
    chip_target_stride: 448
    max_per_img: -1
    nms_thresh: 0.5


